name: reusable variable

on:
  push:
    branches:
      - main

jobs:
  call-workflow-1-in-local-repo:
    uses: philipsabri/reusable-workflows/.github/workflows/reusable-variables.yaml@main
    secrets: inherit
