name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Install YQ
      uses: dcarbone/install-yq-action@v1.1.0
    - run: yq --version
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      id: create_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "main"
        DRY_RUN: "true"
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ steps.create_tag.outputs.tag }} .
    - name: Push to GHCR
      run: docker push ${{ env.IMAGE_NAME }}:${{ steps.create_tag.outputs.tag }}
    - run: yq -i '.image.tag = "${{ steps.create_tag.outputs.tag }}"' deployment/values.yaml
    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update tag"
        git push
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      id: create_tag_real
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "main"
    - run: git tag prod -f && git push origin prod
